**Внимание! Необходимо использовать функции numpy по-максимуму! И практически никаких циклов!**

In [7]:
import numpy as np

### 1. Отсортируйте содержимое матрицы, чтобы в каждом столбце все значения распологались по возрастанию:

In [4]:
np.random.seed(21)
a = np.random.randint(0, 10, (5, 3))
print(a)

[[9 8 4]
 [0 0 8]
 [3 2 1]
 [8 9 6]
 [0 4 6]]


In [19]:
# Дописать код здесь
a_sort = a = a[a[:,0].argsort()]
print(a_sort)

[[0 0 1]
 [0 2 4]
 [3 4 6]
 [8 8 6]
 [9 9 8]]


### 2. Найти наиболее частое значение в массиве
[0 4 2 3 2 0 0 4 5 2 8 4 7 0 4 2 0 3 4 6 0 2 1 8 9 5 9 2 7 7 1 5 6 1 9 1 9
 0 7 0 8 5 6 9 6 9 2 1 8 7]

In [34]:
a1 = np.array([0, 4, 2, 3, 2, 0, 0, 4, 5, 2, 8, 4, 7, 0, 4, 2, 0, 3, 4, 6, 0, 2, 1, 8, 9, 5, 9, 2, 7, 7, 1, 5, 6, 1, 9, 1, 9, 0, 7, 0, 8, 5, 6, 9, 6, 9, 2, 1, 8, 7])

In [38]:
# Дописать код здесь
a_popular = np.argmax(np.bincount(a1))
list(a1).index(a_popular)

0

### 3. Найти n наибольших значений в массиве

In [41]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z

array([4355, 5843, 1729, ..., 2241,  937, 1651])

In [47]:
# Дописать код здесь
Z_index = Z.argsort()[-5:][::-1]
print (np.take(Z, Z_index))

[9999 9998 9997 9996 9995]


### 4. Дан двумерный массив. Найти все различные строки

In [48]:
Z = np.random.randint(0, 2, (6,3))
print(Z)

[[1 1 1]
 [0 0 1]
 [0 0 0]
 [1 0 1]
 [0 0 1]
 [1 0 1]]


In [49]:
# Дописать код здесь
unique_Z_rows = np.unique(Z, axis=0)
unique_Z_rows

array([[0, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 1]])

### 5. Написать функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [113]:
%%timeit -n 5    
A = np.array([1, 2, 3, 4, 5])
summa = [0] * len(A)
summa[0] = A[0]
for i in range(1, len(A)):
    summa[i] = summa[i - 1] + A[i]
    S = summa / np.arange(1, len(A) + 1)
print(S)

[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
[1.  1.5 2.  2.5 3. ]
324 µs ± 67.2 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [ ]:
%%timeit -n 5    #без библиотеки Numpy



In [140]:
A = np.array([1, 2, 3, 4, 5])
summa = [0] * len(A)
summa[0] = A[0]
for i in range(1, len(A)):
    summa[i] = summa[i - 1] + A[i]
    for j in range(1, len(A)+1):
        S = summa / (A[1:].sum()+1)
print(S)

[0.06666667 0.2        0.4        0.66666667 1.        ]


### 6. Пусть задан некоторый массив  𝑋 . Заменить все элементы с нечетными индексами на число  𝑎  (если оно не указано, то на 1), четные - возвести в куб и записать в обратном порядке на те же позиции. Массив  𝑋  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [31]:
X = np.array([100, 200, 300, 400, 500])
Xnew = X.copy(order='C')
a = 1
print(X)

[100 200 300 400 500]


In [32]:
Xnew[1::2] = a
Xnew[::2] = np.power(Xnew[::2], 3)[::-1]
Xnew

array([125000000,         1,  27000000,         1,   1000000])

In [33]:
X = np.concatenate((X, Xnew), axis=0)
print(X)

[      100       200       300       400       500 125000000         1
  27000000         1   1000000]


### 7. Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [61]:
import timeit

a = np.array([[np.random.randint(0,10,10)]]) 
b = np.array([[np.random.randint(0,10,10)]]) 
print(a,' ',b)

[[[6 8 6 3 5 2 4 5 8 9]]]   [[[4 4 9 8 3 0 8 7 5 8]]]


In [72]:
%%timeit -n 5

s = 0
for x, y in zip(a, b):
    s += x * y

print(np.sum(s))

328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
68.4 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [70]:
%%timeit -n 5

s = a.dot(b.reshape(1,10,1))

print(s)

[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
[[[[328]]]]
The slowest run took 4.73 times longer than the fastest. This could mean that an intermediate result is being cached.
225 µs ± 119 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


*Вывод: получается, что через скалярное произведение в Numpy операция происходит в среднем в 1,9-4,2 раза медленнее, чем без него.*

### 8. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5

In [55]:
# Дописать код здесь
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
uslovie = x==0
print (x[1:][uslovie[:-1]].max())

5
